name: Auto Self Report

on: 

  schedule:

    - cron: "30 23 * * *"

jobs:



  report:

    name: Self report

    runs-on: ubuntu-latest

    steps:



    - name: Get executable

      run: |

        curl -L -o auto-self-report https://github.com/mzz2017/auto-selfreport/releases/latest/download/auto-selfreport_linux_amd64

        chmod +x auto-self-report

        

    - name: Run job

      run: ./auto-self-report -u ${{ secrets.SHU_USERNAME }} -p ${{ secrets.SHU_PASSWORD }} -e ${{ secrets.EMAIL }}
